### ISSUE TITLE
Docking support?

### ISSUE THREAD

**Issue by MrManiacc** [SpaiR/imgui-java#1]
First of all, I just wanted to say, this is an amazing binding. I haven't had any problems, and it's working exactly as expected. This is a wonder library. Secondly, I was wondering if you could create bindings for the docking branch of imgui? [Here](https://github.com/ocornut/imgui/tree/docking) is the branch for docking. Thanks again for this awesome library, looking forward to (maybe) getting to use docking though aswell!

**Comment by SpaiR** [comment]
I think it's possible to provide a second branch with "docking". I will need to do it anyway, after it becomes stable though. But the thing is that there is not only the docking features, but multi-viewport too. I will need to port it as well, so it may take a time while it would be done.

Also, right now binding doesn't provide an ability to create classes mapped to instanciated native structs. That's why it doesn't support fonts customizing functionality. I have some thoughts about that so I planning to implement it first. Then I will take a time to see what could be done with "docking" too.

**Comment by PixelRifts** [comment]
Sooo Is Docking not supported yet??

**Comment by MrManiacc** [comment]
Bump, still hoping for docking support!

**Comment by SpaiR** [comment]
[Docking](https://github.com/ocornut/imgui/issues/2109) feature is now available! Use version [v1.76-0.10](https://github.com/SpaiR/imgui-java/tree/v1.76-0.10) or later.

**Comment by MrManiacc** [comment]
I love you, you're a wonderful person

**Comment by PixelRifts** [comment]
YAY!!!
