### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by lwjglgamedev** [SpaiR/imgui-java#151]
### Version

1.86.5

### What happened?

I think windows natives for latest version 1.86.5 are missing from maven repo. Don't know if have to report this or not. You can check it here: 

https://repo.maven.apache.org/maven2/io/github/spair/imgui-java-natives-windows/

No entry for 1.86.5.

### Reproduction

I've just updated dependencies version to 1.86.5 from 1.86.4. With orevious version it builds perfectly.

**Comment by SpaiR** [comment]
@lwjglgamedev Thanks for the issue!
Fixed in https://github.com/SpaiR/imgui-java/commit/cb381e9521c5c1ee6d47d9dd5134ade0f24fc23f and https://github.com/SpaiR/imgui-java/commit/09da8c4aaebb2d262dbc122057e64d23a313136f. Already available in `1.86.6` 

There was also the same problem with macOS. 
I don't know when I would be managed to find the problem without the report 🙏

**Comment by lwjglgamedev** [comment]
Thanks for the great library binding!
