### ISSUE TITLE
Missing Bindings: InputText with some parameter combination

### ISSUE THREAD

**Issue by Moulberry** [SpaiR/imgui-java#166]
### Version

v1.86.9

### What part of the binding has gaps?

Dear ImGui

### What is missing?

The inputText binding has a number of gaps in it. For instance, you can't create a non-multiline inputText with a specific width/height. I was planning on creating a PR that adds such a method, but I felt like the situation could be resolved in one fell swoop by simply making the "preInputText" method which accepts all the parameters public.

Given that the naming of that method is internal, a simple method which delegates to it called "inputText" would suffice.

If for some reason this is not desirable, I can go ahead with the PR adding inputText() bindings with width/height.

**Comment by SpaiR** [comment]
`inputText` has no option to set its width and height. It is only the feature of the `inputTextMultiline`. Yet, you can change `inputText` width with `ImGui#setNextItemWidth` method and change it's height by pushing custom `FramePadding` style, before the widget.

Making `preInputText` public won't change anthying, since its width/height args are used for multi-line input only.

For the reference https://github.com/ocornut/imgui/issues/385
