### ISSUE TITLE
Bug: freetype rendering much worse

### ISSUE THREAD

**Issue by phraktle** [SpaiR/imgui-java#244]
### Version

1.86.12

### What happened?

After upgrading to 1.86.12 (appreciate the work on the library again!), font rendering became markedly worse. This can be attributed to freetype, which actually seems to yield worse results despite my efforts to adjust hinting flags. 

rendering with 1.86.11:
<img width="596" alt="sbt" src="https://github.com/user-attachments/assets/fc3a8d3e-2a21-4e7f-b3c0-85a5e874363b">

rendering with 1.86.12:
<img width="596" alt="freetype" src="https://github.com/user-attachments/assets/d700ac4f-39fd-4954-a480-6fd5521afc68">

Not sure if there are any flags I can set to make it look okay – if not, it would be great to have a distribution without freetype.

### Reproduction

```
var font = "/System/Library/Fonts/SFNSMono.ttf";
var fonts = ImGui.getIO().getFonts();
var cfg = new ImFontConfig();
cfg.setOversampleH(3);
cfg.setOversampleV(3);
cfg.setRasterizerMultiply(2f);
cfg.setPixelSnapH(true);
fonts.addFontFromFileTTF(font, 14, cfg);
```

**Comment by SpaiR** [comment]
Yes, it seems I wasn't imagining things... 😅 

I was waiting for someone else's feedback on this topic because I also noticed this issue. (If it's not too much trouble, could you let me know which OS you're using?)

That said, I've looked into it a bit, and it appears there's a relatively simple way to use STB_TrueType and FreeType simultaneously. I think I'll adapt the API to support this option, making STB_TrueType the default. At least, that will be simpler than maintaining multiple libs. Will do for the next release.

**Comment by phraktle** [comment]
The screenshots are from MacOS Sonoma 14.5.

Btw, it seems the oversampling settings are ignored by the freetype engine. But even without oversampling, SBT gives better results:

<img width="596" alt="sbt_nooversample" src="https://github.com/user-attachments/assets/742cccc8-7355-4d04-a897-e2cf097130dc">
