### ISSUE TITLE
Bug: ImGui.createContext() overwrites the pointer of previously created contexts

### ISSUE THREAD

**Issue by maeda6uiui** [SpaiR/imgui-java#253]
### Version

1.86.12

### What happened?

Double free error occurs when calling `ImGui.destroyContext()` for each context created by `ImGui.createContext()`.
I found this issue when trying to manage multiple windows and create an ImGui context for each window.

### Reproduction

```java
import imgui.ImGui;
import imgui.internal.ImGuiContext;

public class MultipleImGuiContexts {
    public static void main(String[] args) {
        //Create first context
        ImGuiContext context1 = ImGui.createContext();
        System.out.printf("first ptr = %d\n", context1.ptr);

        //Create second context
        ImGuiContext context2 = ImGui.createContext();
        System.out.printf("second ptr = %d\n", context2.ptr);

        //First pointer is overridden by the second one
        System.out.printf("first ptr = %d\n", context1.ptr);
        System.out.printf("second ptr = %d\n", context2.ptr);

        //Destroy contexts
        ImGui.destroyContext(context1);
        ImGui.destroyContext(context2); //double free
    }
}
```

**Comment by maeda6uiui** [comment]
Currently I work around this issue by directly creating an instance of `ImGuiContext`.

```java
imguiContext = ImGui.createContext();
imguiContext = new ImGuiContext(imguiContext.ptr);
```

**Comment by SpaiR** [comment]
Yes, the issue did indeed exist because the context pointer was previously placed in a static object, which could lead to the field being overwritten. However, after PR #240, this issue is no longer relevant, as the new version always creates the context with a new instance. The changes (and fix) will be included in the next release.

For the ref: [before ](https://github.com/SpaiR/imgui-java/blob/d00f7b5a12344afcda71c11c1951eac0652a1556/imgui-binding/src/main/java/imgui/ImGui.java#L196-L199) and [after](https://github.com/SpaiR/imgui-java/blob/main/imgui-binding/src/generated/java/imgui/ImGui.java#L166-L168).
