### ISSUE TITLE
Missing Bindings: ImPlot plot methods with length

### ISSUE THREAD

**Issue by phraktle** [SpaiR/imgui-java#261]
### Version

1.87.1

### What part of the binding has gaps?

implot

### What is missing?

1.86.x exposed the `length` parameter on `plot*` methods. This is no longer available in 1.87.0 bindings, so one can only plot the full buffer. However there are legitimate use-cases where one needs this (eg. resizable buffers).

**Comment by SpaiR** [comment]
This can be done, but there's one issue. In about half of the methods, there is an optional `int` argument that comes right after the buffer size argument, which creates a naming collision. There are a few ways to resolve this - one option is to change the buffer size parameter to a `long` type to create a unique signature. Or to add a suffix like "V" to the method name on the Java side (e.g., `plotLineV`).

Since I don't use this functionality, I'm curious to hear other perspective on what would be the more convenient approach.

cc @calvertdw (I know you're actively using ImPlot in your app, so this might be relevant for you as well.)

**Comment by phraktle** [comment]
Do you mean the `offset` parameter? Maybe you could have two variants: one where neither is specified (which is convenient for the simple cases where you want to plot the full buffer) and one where both `length` and `offset` is specified.

**Comment by SpaiR** [comment]
Yes, that seems like a viable solution. However, I'm interested in your use case. How do you use ImPlot functions in your work?

**Comment by phraktle** [comment]
A common theme for me is visualization of real-time streaming data. Incoming new data is appended to a `double[]` buffer (two actually: timestamps for X, values for Y). When the buffers are full they are expanded (grown by a fixed ratio) – so the plot calls need to disregard the yet-unused region. And since these buffers get quite large over time, I want to avoid copying/double-buffering.

**Comment by calvertdw** [comment]
Finally got a chance to take a minute and understand this.

I am completely on board with @phraktle's suggestion:

>Do you mean the offset parameter? Maybe you could have two variants: one where neither is specified (which is convenient for the simple cases where you want to plot the full buffer) and one where both length and offset is specified.

If that works, either you specify offset and length, or nothing. That would be perfect. I don't really like either appending a random letter or using a long. Using the long would be particularly bad, because it'd be really easy to accidentally pass the length as an int.

**Comment by SpaiR** [comment]
I implemented the approach we discussed here. I believe that should help.
The changes are available in version **[v1.83.3](https://github.com/SpaiR/imgui-java/releases/tag/v1.87.3)**

cc @phraktle @calvertdw

**Comment by phraktle** [comment]
Thank you @SpaiR, 1.87.3 works well (and pretty fonts are also back :)
