### ISSUE TITLE
Missing Bindings: unsigned inputScalar

### ISSUE THREAD

**Issue by a-cpu-a** [SpaiR/imgui-java#267]
### Version

1.87.3

### What part of the binding has gaps?

Dear ImGui

### What is missing?

In 1.86.11 you could use the dataType argument in inputScalar, to use unsigned numbers
```java
public static boolean inputScalar(String label, int dataType, ImLong pData)
```
Example use:
```java
ImGui.inputScalar("UUID-Least",ImGuiDataType.U64,uuid[0]);
```

Since dataType was removed, there is no way to use unsigned numbers
```java
public static boolean inputScalar(final String label, final ImLong pData)
```

**Comment by SpaiR** [comment]
Thank you for bringing this to my attention! 👍 

I have implemented a fix for this as part of PR #268, as well as for the issue you mentioned in PR #266. If you're interested, feel free to double-check that the methods you need have been added.

If there are any other methods that have gone missing due to recent changes, please don't hesitate to reach out.
