### ISSUE TITLE
Missing Bindings: linux problems

### ISSUE THREAD

**Issue by YunusTR** [SpaiR/imgui-java#281]
### Version

1.87.0 linux

### What part of the binding has gaps?

Dear ImGui

### What is missing?

Can you recompile the whole imgui library for linux arm64?

**Comment by SpaiR** [comment]
It is what it is. If you need libraries for a specific platform, you can compile them yourself. Alternatively, you can add the build process for the new platform to the existing CI of the project and do the PR.

**Comment by mcpkdotdev** [comment]
I'm trying to do this by looking at the PR where MacOS got arm support.
I managed to compile it (with some inconsistencies/manual task inbetween because I'm not very good with building) and it passed
ImGui.createContext()

I'm running this on a new setup(fedora + hyprland) so it currently crashes for unknown reasons. I will attempt it again on another linux setup and if it works, I will fix the said inconsistencies/manual tasks and make a PR.

**Comment by mcpkdotdev** [comment]
Made a (draft) pr: https://github.com/SpaiR/imgui-java/pulls
It should build correctly and give a working jar, but CI has to be worked with for automatic building.

**Comment by yunuservices** [comment]
> Made a (draft) pr: https://github.com/SpaiR/imgui-java/pull/324
> It should build correctly and give a working jar, but CI has to be worked with for automatic building.

Thanks, i will test that pr. if i take some errors i will specify it to here.
