### ISSUE TITLE
Missing Bindings: ImSequencer

### ISSUE THREAD

**Issue by tbvns** [SpaiR/imgui-java#289]
### Version

1.86.11

### What part of the binding has gaps?

ImGuizmo

### What is missing?

The java bindings for ImSequencer are not present.
I know this has already been asked over a year ago, but I wanted to know if this was still in the scope of this project.
I don't really know c++ or JNA/JNI, else I would try to do this on my own.
If this is not planned, I will make the effort to try and make it myself.

**Comment by SpaiR** [comment]
Personally, I don't have any plans to add a binding for ImSequencer. And unless I have a need for it in my own work, I won't be focusing on it. So yes, if you want this functionality, I recommend adding it yourself. In fact, all extensions for the binding have been contributed by other contributors.

I'm closing this issue since it duplicates an existing one #176

**Comment by tbvns** [comment]
ok ty

**Comment by tbvns** [comment]
I swear to god I tried, but I can't even find a way to compile ImGuizmo.
