### ISSUE TITLE
Backport to lwjgl 3.2.1

### ISSUE THREAD

**Issue by MrManiacc** [SpaiR/imgui-java#42]
I know. This doesn't really make sense to go back to an older version of lwjgl but hear me out. Please check out this issue which describes why I think a back-port could be useful: [here](https://github.com/MrManiacc/Blueprints/issues/5#issuecomment-819104025), I don't ask you to fully port the master branch but perhaps a secondary branch that supports lwjgl 3.2.1. _TL;DR macos forces lwjgl 3.2.1 for minecraft,_ your ImGui bindings **requires <= 3.2.2**

**Comment by MrManiacc** [comment]
After thinking about it more, I think that simply removing this method **glfwGetMonitorWorkarea** would fix the issue on mac. We could use something like glfwGetMonitorPhysicalSize multiplied by glfwGetMonitorPhysicalSize to find the monitor work area, in theory I believe.

**Comment by SpaiR** [comment]
This is not about imgui, but about the backend. Solution will be not to use the renderer provided by the binding and do your own implementation. Basically, just copy paste glfw/gl classes into your code base (keep packages hierarchy) and compile with any lwjgl 3 compatible version you need to. Without any methods you don't need to. For any purpose you want. That is the only way to resolve such problems, since environment agnostic paradigma is one of the biggest advantage of dear imgui.

**Comment by MrManiacc** [comment]
You're right, it's not about imgui. I'll have to look back into this. The first time I attempted to create my own binding with lwjgl 3.2.1, I removed the getWindowContentArea method (the refence to the method inside your bindings), and it made everything break. It's gonna take a little more finesse. Do you think i'll need to write my own implementation of the method, or is there an alterative? If you have any ideas it'd be super helpful. I'll keep you up to date with my findings.

**Comment by SpaiR** [comment]
Don't use multi-viewports and remove the line which calls `glfwGetMonitorWorkarea`. That will be enough...

**Comment by MrManiacc** [comment]
Perfect, that's all I needed, I'm gonna look into this later today. I'll report back and close the issue once I figure it out.
