### ISSUE TITLE
Doesn't build on ubuntu 20.04

### ISSUE THREAD

**Issue by RaphiMC** [SpaiR/imgui-java#46]
I tried to build the natives and it always fails with the same error.

Build log: https://pastebin.com/Km0MRPWj

**Comment by SpaiR** [comment]
You have probably didn't pull git submodules.

**Comment by RaphiMC** [comment]
Yes that fixed the issue, would be cool if you could write that somewhere so its clear how to clone the repository correctly.
How can I build the windows/mac 32/64bit natives? Do I really need Windows/Mac for that or can I do that on linux?
You can close the issue if you want.

**Comment by RaphiMC** [comment]
I don't know if I did it right, but I replaced the -Denvs with another target and it worked for windows, but some didn't work.

Here are the logs:
linux32: https://pastebin.com/YFBqELPp
mac64: https://pastebin.com/Zg5nXVr9

**Comment by SpaiR** [comment]
You can't compile for linux32 because of missing dependecies: https://stackoverflow.com/questions/4643197/missing-include-bits-cconfig-h-when-cross-compiling-64-bit-program-on-32-bit

Speaking about cross-compilation itself, you can compile windows binaries on linux, but you need Mac to build MacOS libraries. That can't be fixed, since compilation process requires xcode, which is available only for mac though...
