### ISSUE TITLE
Building on linux error

### ISSUE THREAD

**Issue by MrManiacc** [SpaiR/imgui-java#5]
`Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/imgui-java-bin_jraynor/libimgui-java64.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/imgui-java-bin_jraynor/libimgui-java64.so)`

I think you've built the linux bindings with a unreleased verision of GLIBC, the current release is 2.28, so could you possibily rebuild those natives with a other version of GLIBC so it will work for more users? (Coming from zorin 15.2)

**Comment by MrManiacc** [comment]
I've also verified the library exists it's solely something to do with what version the natives were compiled with. I could compile my self, but I feel it'd be better if you did so it'd be upon the main repo.

**Comment by SpaiR** [comment]
Compiling with lower version won't help since, I'm sure, there always will be users with different versions of their libs. I can't cover all needs by myself. 

> the current release is 2.28

https://www.gnu.org/software/libc/
The latest release version is 2.31. I do use the same version. As far as I can understand, zorin is based on the ubuntu. I can see an available package with glibc 2.31 for it as well.

Thus I would recommend to update your system dependencies. If, for some reason, you can't do it, still you can use native binaries compiled by yourself. With dependencies for your needs.
