### ISSUE TITLE
[Missing binding] ImGui::SliderBehavior

### ISSUE THREAD

**Issue by RaphiMC** [SpaiR/imgui-java#77]
The binding for ImGui::SliderBehavior is missing in the java wrapper.
https://github.com/ocornut/imgui/blob/master/imgui_internal.h#L2626
https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L2786

**Comment by SpaiR** [comment]
There is no point to tell that some internal API is missing. In fact, **all** internal API is missing. It's too big to port and support its compatibility manually. Until any generation-routine will be introduced, binding won't has a goal to provide internal API as it's done for the public one. 

So I would recommend instead of creating issues to create PRs with stuff you need. I will merge it and make a new release with it. The process of porting is very straightforward. I'll be glad to provide more information if you need so.
