### ISSUE TITLE
Text corrupting.

### ISSUE THREAD

**Issue by maxgamesNL** [SpaiR/imgui-java#85]
I am using imgui java for the GUI of a Minecraft client.
But it seems to be very inconsistent.
Sometimes the text renders as it is supposed to, but at other times it is just corrupted.
When I close the GUI and reopen it changes how the corrupted text looks and after a few times of reopening it load correctly.
This issue seems to have something to do with the resizing of the window.
The file where I render it is https://github.com/maxgamesNL/Galactite/blob/inDev/src/main/java/me/maxmods/learnfabric/features/gui/TestGUI.java
The inDev tree is error-free next to this so you could try to run and edit it and you shouldn't be stopped by other problems.

**Comment by SpaiR** [comment]
I've shared my thoughts about a similar problem here https://github.com/SpaiR/imgui-java/issues/20 tldr; Every time you create a `Screen`, you re-initialize the ImGui state. At the same time you don't dispose it at any point, so there is nothing surprise that the font's atlas texture is corrupted. Do the state disposing or initialize ImGui only once per application. Also, there are several minecraft mods which are already using imgui-java.  You can look through them for examples.

Closing the issues since it's not related to the Dear ImGui or the binding itself.
